title: Memory Graph SQL
description: Documentation for Memory Graph SQL Server with Enhanced Semantic Layer
theme: just-the-docs

url: https://dmontgomery40.github.io/memory-graph-sql

aux_links:
  Repository: https://github.com/DMontgomery40/memory-graph-sql

color_scheme: light
search_enabled: true
heading_anchors: true